# Copyright 2024 ENPM818N_Group_Project4
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.53.0
  name: opentelemetry-demo-jaeger-collector
spec:
  clusterIP: None
  ports:
  - appProtocol: http
    name: http-zipkin
    port: 9411
    targetPort: 0
  - appProtocol: grpc
    name: grpc-http
    port: 14250
    targetPort: 0
  - name: c-tchan-trft
    port: 14267
    targetPort: 0
  - appProtocol: http
    name: http-c-binary-trft
    port: 14268
    targetPort: 0
  - appProtocol: grpc
    name: otlp-grpc
    port: 4317
    targetPort: 0
  - appProtocol: http
    name: otlp-http
    port: 4318
    targetPort: 0
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: jaeger
