# Copyright 2024 ENPM818N_Group_Project4
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: valkey
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-valkey
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-valkey
  name: opentelemetry-demo-valkey
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-valkey
  template:
    metadata:
      labels:
        app.kubernetes.io/component: valkey
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: opentelemetry-demo-valkey
        opentelemetry.io/name: opentelemetry-demo-valkey
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: opentelemetry-demo-otelcol
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
        image: valkey/valkey:7.2-alpine
        imagePullPolicy: IfNotPresent
        name: valkey
        ports:
        - containerPort: 6379
          name: valkey
        resources:
          limits:
            memory: 20Mi
        securityContext:
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts: null
      serviceAccountName: opentelemetry-demo
      volumes: null
